### **Create a 1D NumPy array of integers from 1 to 20 (inclusive) using np.arange().**

In [2]:
import numpy as np

np.arange(1, 21)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### **Create a 4×5 array of zeros. Then create another 4×5 array of ones. Add them together.**

In [5]:
A = np.zeros((4,5))
B = np.ones((4, 5))
A+B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### **Create an array of 8 evenly spaced values between 0 and 1 using np.linspace(). Print the values.**

In [6]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

### Create np.arange(1, 25) and reshape it into a 4×6 array. Print the shape, number of dimensions (ndim), and data type (dtype).

In [11]:
a = np.arange(1,25)
b = np.reshape(a, (4,6))
np.shape(b)

(4, 6)

In [13]:
b.ndim

2

In [10]:
b.dtype

dtype('int64')

### From the array [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], extract: (a) first 5 elements, (b) last 3 elements, (c) every alternate element.**bold text**

In [17]:
a =  [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
a[:5]

[10, 20, 30, 40, 50]

In [22]:
a[-3:]

[80, 90, 100]

In [20]:
a[::2]

[10, 30, 50, 70, 90]

### **Create a 5×5 array using np.arange(25).reshape(5,5). Extract: (a) row 2, (b) column 3, (c) top-right 3×3 block.**

In [25]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
a[1]

array([5, 6, 7, 8, 9])

In [28]:
a[:, 2]

array([ 2,  7, 12, 17, 22])

In [34]:
a[:-2,-3:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

### **Create array a = [1, 2, 3, 4, 5]. Add 100 to every element. Multiply every element by 3. Both without any loop.**

In [37]:
a = [1, 2, 3, 4, 5]

In [39]:

np.array(a) + 100

array([101, 102, 103, 104, 105])

In [40]:
np.array(a) * 3

array([ 3,  6,  9, 12, 15])

### Create two arrays: a = [10, 20, 30] and b = [1, 2, 3]. Compute: a+b, a-b, a*b, a/b element-wise. **bold text**

In [41]:
a = np.array([10,20,30])
b = np.array([1, 2,3])

In [42]:
a+b

array([11, 22, 33])

In [44]:
a-b

array([ 9, 18, 27])

In [43]:
a*b

array([10, 40, 90])

In [45]:
a/b

array([10., 10., 10.])

### **Given scores = [72, 85, 91, 68, 74, 88, 62, 95, 77, 80], compute: mean, median (np.median), std, min, max, and range (max-min).**

In [47]:
scores = np.array([72, 85, 91, 68, 74, 88, 62, 95, 77, 80])

In [48]:
np.mean(scores)

np.float64(79.2)

In [49]:
np.median(scores)

np.float64(78.5)

In [50]:
np.std(scores)

np.float64(10.02796090937734)

In [51]:
np.min(scores)

np.int64(62)

In [52]:
np.max(scores)

np.int64(95)

In [54]:
np.max(scores) - np.min(scores)

np.int64(33)

### **For a 3×4 random integer array (np.random.randint(1,100,size=(3,4))): compute sum across all elements, row-wise sum (axis=1), and column-wise mean (axis=0).**

### **For a 3×4 random integer array (np.random.randint(1,100,size=(3,4))): compute sum across all elements, row-wise sum (axis=1), and column-wise mean (axis=0).**

In [57]:
a = np.random.randint(1,100,size=(3,4))
a

array([[38, 45, 93, 98],
       [80,  7,  6, 18],
       [91, 69, 11, 42]])

In [58]:
print("Sum of all elements:", np.sum(a))

Sum of all elements: 598


In [59]:
print("Row-wise sum:", np.sum(a, axis=1))

Row-wise sum: [274 111 213]


In [60]:
print("Column-wise mean:", np.mean(a, axis=0))

Column-wise mean: [69.66666667 40.33333333 36.66666667 52.66666667]


### **Generate 1000 random numbers from a normal distribution (np.random.normal(mean=50, std=10, size=1000)). Compute mean and std. Are they close to 50 and 10?**

In [67]:
random_numbers = np.random.normal(loc=50, scale=10, size=1000)

In [68]:
np.mean(random_numbers)

np.float64(49.92752866231397)

In [69]:
np.std(random_numbers)

np.float64(10.174154876893931)